---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: True
  vars:
     user_name: serge2026
     group: terraform 
  vars_files:
    - variables.yml
  tasks:
    - name: check server uptime
      command: "{{my_command}}"
      register: my_uptime
    - name: list directory
      shell: ls
    - name: check the kernel version
      command: uname -r
      register: kernel_output
    - name: create user
      user:
        name: "{{user_name}}"
    - name: create group
      group:
        name: "{{group}}"
    - name: Read data 
      debug:
        var: my_uptime.stdout[:19]